# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('mail', models.EmailField(max_length=254, verbose_name='mail')),
                ('message', models.TextField(help_text='mensaje del cliente', verbose_name='message')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
