# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre o Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(help_text='Un mensaje')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Persona o Empresa',
                'verbose_name_plural': 'Personas o Empresas',
            },
        ),
    ]
