# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, unique=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='mensaje del cliente', unique=True, verbose_name='mensaje'),
        ),
    ]
