# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 05:56
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('archivo', models.FileField(upload_to='uploads/D/%Y/%m/%d/', verbose_name='archivo')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_created=True, editable=False, null=True, verbose_name='creaci\xf3n')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='modificaci\xf3n')),
                ('fecha_publicacion', models.DateTimeField(default=datetime.datetime(2017, 10, 26, 2, 56, 57, 524581), help_text='Para que una publicaci\xf3n sea publicada, debe estar activa y su fecha de publicaci\xf3n debe estar en el pasado', verbose_name='fecha de publicaci\xf3n')),
                ('slug', models.SlugField(help_text='Debe ser unica en el mes y sirve para generar la url asociada, se genera automaticamente', unique_for_date='pub_date', verbose_name='slug')),
                ('url_externa', models.URLField(blank=True, help_text='Si se deja vac\xedo este campo, los links para ver m\xe1s detalles redireccionar\xe1n dentro del sitio al detalle. Al ingresar una URL en este campo se redireccionar\xe1 a este cuando se pidan detalles ', null=True, verbose_name='url externa')),
                ('tipo_publicacion', models.CharField(choices=[('NU', 'Nuevo'), ('PR', 'Proyecto'), ('PO', 'Posteo'), ('OT', 'Otro'), ('EV', 'Evento')], default='PO', help_text='Puede ser cualquier cosa: Eventos, posteos, proyectos, etc..', max_length=1, verbose_name='tipo de publicaci\xf3n')),
                ('titulo', models.CharField(help_text='Titulo de la publicaci\xf3n', max_length=200, verbose_name='titulo')),
                ('subtitulo', models.CharField(blank=True, help_text='Subtitulo de la publicaci\xf3n', max_length=200, null=True, verbose_name='subtitulo')),
                ('ubicacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='ubicaci\xf3n')),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenido')),
                ('visible', models.BooleanField(default=False, help_text='Marque para hacer esta entrada en vivo (ver tambi\xe9n la fecha de publicaci\xf3n). Tenga en cuenta que los administradores (como usted) tienen permiso para previsualizar Entradas inactivas mientras que el p\xfablico en general no', verbose_name='se encuentra visible')),
                ('slider', models.BooleanField(default=False, help_text='Marque para que sea visible en el slider Se visualizar\xe1 primero el inicial y luego los que sean visibles en slider Pueden marcar hasta 6 para ser visibles, es necesaria una imagen, de no ser subida una im\xe1gen no se mostrar\xe1 ', verbose_name='activo en el slider')),
                ('comentarios_facebook', models.BooleanField(default=False, help_text='Marque para que sea visible el plugin de facebook para realizar comentarios No se tendr\xe1 mayor control sobre los comentarios ', verbose_name='comentarios de Facebook')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'ordering': ('-fecha_publicacion',),
                'get_latest_by': 'fecha_publicacion',
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
            ],
            options={
                'ordering': ('titulo',),
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='ej: Horario, tickets, presentaci\xf3n, etc', max_length=100, null=True, verbose_name='nombre')),
                ('archivo', models.FileField(upload_to='uploads/I/%Y/%m/%d/', verbose_name='archivo')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_entrada', to='blog.Entrada', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('archivo', models.FileField(upload_to='uploads/V/%Y/%m/%d/', verbose_name='archivo')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_entrada', to='blog.Entrada', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, related_name='entry_tag', to='blog.Etiqueta', verbose_name='etiqueta'),
        ),
        migrations.AddField(
            model_name='documento',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_entrada', to='blog.Entrada', verbose_name='entrada'),
        ),
    ]
