# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:32
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, editable=False, null=True, verbose_name='created')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='modify')),
                ('pub_date', models.DateTimeField(help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='publication date')),
                ('slug', models.SlugField(unique_for_date='pub_date', verbose_name='slug')),
                ('publication_type', models.CharField(choices=[('N', 'News'), ('P', 'Projects'), ('E', 'Entry'), ('O', 'Others'), ('V', 'Events')], default='E', max_length=1, verbose_name='publication type')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='external url')),
                ('headline', models.CharField(max_length=200, verbose_name='headline')),
                ('subheadline', models.CharField(blank=True, max_length=200, null=True, verbose_name='subheadline')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='location')),
                ('summary', models.CharField(blank=True, max_length=300, null=True, verbose_name='summary')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this entry live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive entries whereas the general public aren't.", verbose_name='is active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pub_date',),
                'get_latest_by': 'pub_date',
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='entries/file')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_entry', to='blog.Entry')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', easy_thumbnails.fields.ThumbnailerImageField(upload_to='entries/img')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post', to='blog.Entry')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='entries/vid')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_post', to='blog.Entry')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
