# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='resumen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 3, 0, 59, 644913), help_text='Para que una publicaci\xf3n sea publicada, debe estar activa y su fecha de publicaci\xf3n debe estar en el pasado', verbose_name='fecha de publicaci\xf3n'),
        ),
    ]
