# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 6, 43, 38, 203932), help_text='Para que una publicaci\xf3n sea publicada, debe estar activa y su fecha de publicaci\xf3n debe estar en el pasado', verbose_name='pub date'),
        ),
    ]
