# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:46
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170825_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'pub_date', 'ordering': ('-pub_date',), 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'archivo', 'verbose_name_plural': 'archivos'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(auto_created=True, editable=False, null=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Marque para hacer esta entrada en vivo (ver tambi\xe9n la fecha de publicaci\xf3n)Tenga en cuenta que los administradores (como usted) tienen permiso para previsualizar Entradas inactivas mientras que el p\xfablico en general no lo son', verbose_name='se encuentra activo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='lugar'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='modify',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 5, 46, 19, 216536), help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='fecha publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='publication_type',
            field=models.CharField(choices=[('N', 'Noticias'), ('P', 'Proyectos'), ('E', 'Entradas'), ('O', 'Otros'), ('V', 'Eventos')], default='E', max_length=1, verbose_name='tipo de publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='subheadline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitulo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='entries/file', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='entries/img', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='entries/vid', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
