# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171026_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug que genera la url de la etiqueta', null=True, unique_for_date='fecha_publicacion', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Para que una publicaci\xf3n sea publicada, debe estar activa y su fecha de publicaci\xf3n debe estar en el pasado', verbose_name='fecha de publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(help_text='Debe ser unica en el mes y sirve para generar la url asociada, se genera automaticamente', unique_for_date='fecha_publicacion', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='tipo_publicacion',
            field=models.CharField(choices=[('NU', 'Nuevo'), ('PR', 'Proyecto'), ('PO', 'Posteo'), ('OT', 'Otro'), ('EV', 'Evento')], default='PO', help_text='Puede ser cualquier cosa: Eventos, posteos, proyectos, etc..', max_length=2, verbose_name='tipo de publicaci\xf3n'),
        ),
    ]
