# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170825_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='on_slider',
            field=models.BooleanField(default=False, help_text='Marque para que sea visible en el sliderSe visualizar\xe1 primero el inicial y luego los que sean visibles en sliderPueden marcar hasta 6 para ser visibles, es necesaria una imagen, de no ser subida una im\xe1gen no se mostrar\xe1', verbose_name='visible en slider'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 7, 13, 59, 840375), help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='fecha publicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='entry_tag', to='blog.Tag', verbose_name='etiqueta'),
        ),
    ]
