# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170827_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='url externa'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Marque para hacer esta entrada en vivo (ver tambi\xe9n la fecha de publicaci\xf3n) Tenga en cuenta que los administradores (como usted) tienen permiso para previsualizar  Entradas inactivas mientras que el p\xfablico en general no lo son ', verbose_name='se encuentra activo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='on_slider',
            field=models.BooleanField(default=False, help_text='Marque para que sea visible en el slider Se visualizar\xe1 primero el inicial y luego los que sean visibles en slider Pueden marcar hasta 6 para ser visibles, es necesaria una imagen, de no ser subida una im\xe1gen no se mostrar\xe1 ', verbose_name='visible en slider'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 10, 30, 20, 878392), help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='fecha publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entry_tag', to='blog.Tag', verbose_name='etiqueta'),
        ),
    ]
