# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170827_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='facebook_comments',
            field=models.BooleanField(default=False, help_text='Marque para que sea visible el plugin de facebook para realizar comentarios No se tendr\xe1 mayor control sobre los comentarios ', verbose_name='habilitar comentarios de facebook'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 21, 58, 32, 617044), help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='fecha publicaci\xf3n'),
        ),
    ]
