# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170828_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='external_url',
            field=models.URLField(blank=True, help_text='Si se deja vac\xedo este campo, los links para ver m\xe1s detalles redireccionar\xe1n dentro del sitio al detalle. Al ingresar una URL en este campo se redireccionar\xe1 a este cuando se pidan detalles ', null=True, verbose_name='url externa'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Marque para hacer esta entrada en vivo (ver tambi\xe9n la fecha de publicaci\xf3n). Tenga en cuenta que los administradores (como usted) tienen permiso para previsualizar Entradas inactivas mientras que el p\xfablico en general no', verbose_name='se encuentra activo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 9, 32, 41, 882407), help_text='Para que una publicaci\xf3n sea publicada, debe estar activa y su fecha de publicaci\xf3n debe estar en el pasado', verbose_name='fecha publicaci\xf3n'),
        ),
    ]
